INSERT INTO ROLE(ID, NAME) VALUES (1, 'ADMIN');
INSERT INTO ROLE(ID, NAME) VALUES (2, 'BUYER');
INSERT INTO ROLE(ID, NAME) VALUES (3, 'SELLER');

-- INSERT into USER (ID, EMAIL, NAME, PASSWORD, STATUS, USERNAME, ROLE_ID)  VALUES ( 1,'Reziz@gmail','Reeziz','$2y$12$ZULYuC/Cz4RQhK4DngP8s.SfhJA35gNayrpKGZTHCryBvcnKL8u4a',0,'dean',1);
-- INSERT into USER (ID, EMAIL, NAME, PASSWORD, STATUS, USERNAME, ROLE_ID)  VALUES ( 2,'Reziz@gmail','buyer','123',0,'reziz',2);
-- INSERT into USER (ID, EMAIL, NAME, PASSWORD, STATUS, USERNAME, ROLE_ID)  VALUES ( 3,'Reziz@gmail','seller','123',1,'reziz',3);
-- INSERT into USER (ID, EMAIL, NAME, PASSWORD, STATUS, USERNAME, ROLE_ID)  VALUES ( 4,'Reziz@gmail','seller','123',0,'reziz',3);
--
--
